# Generated by Django 2.1 on 2018-09-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(help_text='Enter price', max_length=200)),
                ('oldprice', models.CharField(help_text='Enter old price', max_length=200)),
                ('discount', models.CharField(help_text='Enter a discount', max_length=200)),
            ],
        ),
    ]
