# Generated by Django 2.1 on 2018-09-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newitem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.CharField(help_text='Enter a discount', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Oldprice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldprice', models.CharField(help_text='Enter old price', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='price',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='price',
            name='oldprice',
        ),
    ]
